/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 beach.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/beach.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.glass} position={[2.298, 9.592, -2.08]} scale={2.78} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[2.396, -0.016, -4.308]} scale={6.825} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.007']} position={[7.321, 8.926, -6.185]} rotation={[0, 0.416, 0]} scale={2.067} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.003']} position={[1.808, 8.605, -9.064]} rotation={[0, 0.416, 0]} scale={1.789} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.008']} position={[-2.41, 7.743, -6.935]} rotation={[0, 0.416, 0]} scale={0.938} />
    </group>
  )
}

useGLTF.preload('/beach.glb')
