/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fuckblender.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Dunno(props) {
  const { nodes, materials } = useGLTF('/fuckblender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[-2.083, 12.321, 8.233]} rotation={[-2.759, -0.413, 0.987]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[-2.069, 12.332, 8.231]} rotation={[-2.759, -0.413, 0.987]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[-2.009, 12.383, 8.223]} rotation={[-2.759, -0.413, 0.987]} scale={1.103} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[-2.083, 12.321, 8.233]} rotation={[-2.759, -0.413, 0.987]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-1.739, 5.826, 5.636]} rotation={[1.699, -1.377, 2.308]} scale={0.94} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[4.963, 4.227, -0.221]} rotation={[-2.804, -0.34, -2.475]} />
      <mesh geometry={nodes.mug.geometry} material={materials['Material.001']} position={[2.028, 2.473, -6.27]} rotation={[2.539, 0.93, -2.982]} scale={1.404} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[-0.773, 10.162, -10.714]} rotation={[-2.193, 0.19, 0.468]} scale={1.161} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.001']} position={[-0.182, 10.807, -9.903]} rotation={[-2.301, 0.364, 0.505]} scale={1.159} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.001']} position={[-1.234, 9.69, -11.505]} rotation={[-2.301, 0.364, 0.505]} scale={0.565} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[1.003, 12.627, -9.791]} rotation={[-2.301, 0.364, 2.076]} scale={3.301} />
      <mesh geometry={nodes.Circle005.geometry} material={materials['Material.001']} position={[1.605, 12.548, -6.687]} rotation={[-2.423, 0.533, -2.591]} scale={1.161} />
      <mesh geometry={nodes.Circle006.geometry} material={materials['Material.001']} position={[1.123, 12.118, -7.691]} rotation={[-2.301, 0.364, -2.636]} scale={1.159} />
      <mesh geometry={nodes.Circle007.geometry} material={materials['Material.001']} position={[1.562, 12.509, -6.763]} rotation={[0.841, -0.364, 2.636]} scale={1.192} />
      <mesh geometry={nodes.Circle008.geometry} material={materials['Material.001']} position={[2.066, 13.021, -5.896]} rotation={[-2.301, 0.364, -2.636]} scale={0.565} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-1.934, 6.996, -5.062]} rotation={[2.606, -0.469, 0.411]} scale={[-0.108, -0.148, -0.148]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.001']} position={[3.279, 14.58, 6.081]} rotation={[-1.901, 0.214, 0.262]} />
      <mesh geometry={nodes.Circle009.geometry} material={materials['Material.001']} position={[5.105, 15.556, 5.903]} rotation={[-1.901, 0.214, 0.262]} scale={2.239} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[6.747, 18.97, 3.143]} rotation={[-2.811, -0.166, 2.236]} scale={[1.043, 1.043, 0.463]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[0.726, 10.77, -0.801]} rotation={[-3.032, -0.063, -2.678]} scale={0.24} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.001']} position={[0.415, 3.719, 1.139]} rotation={[-0.061, 0.168, -0.283]} scale={1.155} />
      <mesh geometry={nodes.COIN.geometry} material={materials['Material.001']} position={[2.042, 16.16, -4.03]} rotation={[0.957, 0.809, -1.431]} scale={1.123} />
      <mesh geometry={nodes.COIN001.geometry} material={materials['Material.001']} position={[4.76, 10.996, -5.002]} rotation={[0.896, -0.13, -0.1]} />
      <mesh geometry={nodes.COIN002.geometry} material={materials['Material.001']} position={[-1.237, 15.067, -0.296]} rotation={[-1.681, 0.752, 1.243]} />
      <mesh geometry={nodes.COIN003.geometry} material={materials['Material.001']} position={[-1.832, 9.172, 5.873]} rotation={[2.105, -0.13, -0.1]} />
      <mesh geometry={nodes.COIN004.geometry} material={materials['Material.001']} position={[-4.933, 14.825, 8.376]} rotation={[-0.875, 0.041, -0.311]} />
      <mesh geometry={nodes.COIN005.geometry} material={materials['Material.001']} position={[5.984, 6.672, -8.99]} rotation={[2.253, -0.066, 2.8]} />
      <mesh geometry={nodes.COIN006.geometry} material={materials['Material.001']} position={[-0.109, 9.935, 4.231]} rotation={[1.853, 0.752, 1.243]} scale={[0.965, 0.871, 0.809]} />
      <mesh geometry={nodes.COIN007.geometry} material={materials['Material.001']} position={[1.157, 5.557, -0.68]} rotation={[2.935, -0.445, -2.13]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-2.171, 3.465, 3.799]} rotation={[-2.014, 0.816, 1.614]} scale={0.546} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[0.045, 12.713, -4.226]} rotation={[-2.74, 0.268, -3.007]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} position={[0.006, 12.678, -4.149]} rotation={[-2.74, 0.268, -3.007]} scale={1.077} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[0.045, 12.713, -4.226]} rotation={[-2.74, 0.268, -3.007]} />
    </group>
  )
}

useGLTF.preload('/fuckblender.glb')
